/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NewSessionResponseValue struct for NewSessionResponseValue
type NewSessionResponseValue struct {
	SessionId string `json:"sessionId"`
	Capabilities Capabilities `json:"capabilities"`
}

// NewNewSessionResponseValue instantiates a new NewSessionResponseValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewSessionResponseValue(sessionId string, capabilities Capabilities) *NewSessionResponseValue {
	this := NewSessionResponseValue{}
	this.SessionId = sessionId
	this.Capabilities = capabilities
	return &this
}

// NewNewSessionResponseValueWithDefaults instantiates a new NewSessionResponseValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewSessionResponseValueWithDefaults() *NewSessionResponseValue {
	this := NewSessionResponseValue{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *NewSessionResponseValue) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *NewSessionResponseValue) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *NewSessionResponseValue) SetSessionId(v string) {
	o.SessionId = v
}

// GetCapabilities returns the Capabilities field value
func (o *NewSessionResponseValue) GetCapabilities() Capabilities {
	if o == nil {
		var ret Capabilities
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *NewSessionResponseValue) GetCapabilitiesOk() (*Capabilities, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capabilities, true
}

// SetCapabilities sets field value
func (o *NewSessionResponseValue) SetCapabilities(v Capabilities) {
	o.Capabilities = v
}

func (o NewSessionResponseValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sessionId"] = o.SessionId
	}
	if true {
		toSerialize["capabilities"] = o.Capabilities
	}
	return json.Marshal(toSerialize)
}

type NilableNewSessionResponseValue struct {
	value *NewSessionResponseValue
	isSet bool
}

func (v NilableNewSessionResponseValue) Get() *NewSessionResponseValue {
	return v.value
}

func (v *NilableNewSessionResponseValue) Set(val *NewSessionResponseValue) {
	v.value = val
	v.isSet = true
}

func (v NilableNewSessionResponseValue) IsSet() bool {
	return v.isSet
}

func (v *NilableNewSessionResponseValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableNewSessionResponseValue(val *NewSessionResponseValue) *NilableNewSessionResponseValue {
	return &NilableNewSessionResponseValue{value: val, isSet: true}
}

func (v NilableNewSessionResponseValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableNewSessionResponseValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


