/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ArrayResponse struct for ArrayResponse
type ArrayResponse struct {
	Value []string `json:"value"`
}

// NewArrayResponse instantiates a new ArrayResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArrayResponse(value []string) *ArrayResponse {
	this := ArrayResponse{}
	this.Value = value
	return &this
}

// NewArrayResponseWithDefaults instantiates a new ArrayResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArrayResponseWithDefaults() *ArrayResponse {
	this := ArrayResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *ArrayResponse) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ArrayResponse) GetValueOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *ArrayResponse) SetValue(v []string) {
	o.Value = v
}

func (o ArrayResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableArrayResponse struct {
	value *ArrayResponse
	isSet bool
}

func (v NilableArrayResponse) Get() *ArrayResponse {
	return v.value
}

func (v *NilableArrayResponse) Set(val *ArrayResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableArrayResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableArrayResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableArrayResponse(val *ArrayResponse) *NilableArrayResponse {
	return &NilableArrayResponse{value: val, isSet: true}
}

func (v NilableArrayResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableArrayResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


