/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// FirefoxOptionsLog struct for FirefoxOptionsLog
type FirefoxOptionsLog struct {
	Level string `json:"level"`
}

// NewFirefoxOptionsLog instantiates a new FirefoxOptionsLog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirefoxOptionsLog(level string) *FirefoxOptionsLog {
	this := FirefoxOptionsLog{}
	this.Level = level
	return &this
}

// NewFirefoxOptionsLogWithDefaults instantiates a new FirefoxOptionsLog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirefoxOptionsLogWithDefaults() *FirefoxOptionsLog {
	this := FirefoxOptionsLog{}
	return &this
}

// GetLevel returns the Level field value
func (o *FirefoxOptionsLog) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *FirefoxOptionsLog) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *FirefoxOptionsLog) SetLevel(v string) {
	o.Level = v
}

func (o FirefoxOptionsLog) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["level"] = o.Level
	}
	return json.Marshal(toSerialize)
}

type NilableFirefoxOptionsLog struct {
	value *FirefoxOptionsLog
	isSet bool
}

func (v NilableFirefoxOptionsLog) Get() *FirefoxOptionsLog {
	return v.value
}

func (v *NilableFirefoxOptionsLog) Set(val *FirefoxOptionsLog) {
	v.value = val
	v.isSet = true
}

func (v NilableFirefoxOptionsLog) IsSet() bool {
	return v.isSet
}

func (v *NilableFirefoxOptionsLog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableFirefoxOptionsLog(val *FirefoxOptionsLog) *NilableFirefoxOptionsLog {
	return &NilableFirefoxOptionsLog{value: val, isSet: true}
}

func (v NilableFirefoxOptionsLog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableFirefoxOptionsLog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


