/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// FrameId - struct for FrameId
type FrameId struct {
	WebElement *WebElement
	Int32 *int32
}

// WebElementAsFrameId is a convenience function that returns WebElement wrapped in FrameId
func WebElementAsFrameId(v *WebElement) FrameId {
	return FrameId{
		WebElement: v,
	}
}

// int32AsFrameId is a convenience function that returns int32 wrapped in FrameId
func Int32AsFrameId(v *int32) FrameId {
	return FrameId{
		Int32: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *FrameId) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into WebElement
	err = newStrictDecoder(data).Decode(&dst.WebElement)
	if err == nil {
		jsonWebElement, _ := json.Marshal(dst.WebElement)
		if string(jsonWebElement) == "{}" { // empty struct
			dst.WebElement = nil
		} else {
			match++
		}
	} else {
		dst.WebElement = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.WebElement = nil
		dst.Int32 = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(FrameId)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(FrameId)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FrameId) MarshalJSON() ([]byte, error) {
	if src.WebElement != nil {
		return json.Marshal(&src.WebElement)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FrameId) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.WebElement != nil {
		return obj.WebElement
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NilableFrameId struct {
	value *FrameId
	isSet bool
}

func (v NilableFrameId) Get() *FrameId {
	return v.value
}

func (v *NilableFrameId) Set(val *FrameId) {
	v.value = val
	v.isSet = true
}

func (v NilableFrameId) IsSet() bool {
	return v.isSet
}

func (v *NilableFrameId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableFrameId(val *FrameId) *NilableFrameId {
	return &NilableFrameId{value: val, isSet: true}
}

func (v NilableFrameId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableFrameId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


