/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Proxy struct for Proxy
type Proxy struct {
	ProxyType string `json:"proxyType"`
	ProxyAutoconfigUrl *string `json:"proxyAutoconfigUrl,omitempty"`
	FtpProxy *string `json:"ftpProxy,omitempty"`
	HttpProxy *string `json:"httpProxy,omitempty"`
	NoProxy []string `json:"noProxy,omitempty"`
	SslProxy *string `json:"sslProxy,omitempty"`
	SocksProxy *string `json:"socksProxy,omitempty"`
	SocksVersion *int32 `json:"socksVersion,omitempty"`
}

// NewProxy instantiates a new Proxy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxy(proxyType string) *Proxy {
	this := Proxy{}
	this.ProxyType = proxyType
	return &this
}

// NewProxyWithDefaults instantiates a new Proxy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyWithDefaults() *Proxy {
	this := Proxy{}
	return &this
}

// GetProxyType returns the ProxyType field value
func (o *Proxy) GetProxyType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProxyType
}

// GetProxyTypeOk returns a tuple with the ProxyType field value
// and a boolean to check if the value has been set.
func (o *Proxy) GetProxyTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProxyType, true
}

// SetProxyType sets field value
func (o *Proxy) SetProxyType(v string) {
	o.ProxyType = v
}

// GetProxyAutoconfigUrl returns the ProxyAutoconfigUrl field value if set, zero value otherwise.
func (o *Proxy) GetProxyAutoconfigUrl() string {
	if o == nil || o.ProxyAutoconfigUrl == nil {
		var ret string
		return ret
	}
	return *o.ProxyAutoconfigUrl
}

// GetProxyAutoconfigUrlOk returns a tuple with the ProxyAutoconfigUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetProxyAutoconfigUrlOk() (*string, bool) {
	if o == nil || o.ProxyAutoconfigUrl == nil {
		return nil, false
	}
	return o.ProxyAutoconfigUrl, true
}

// HasProxyAutoconfigUrl returns a boolean if a field has been set.
func (o *Proxy) HasProxyAutoconfigUrl() bool {
	if o != nil && o.ProxyAutoconfigUrl != nil {
		return true
	}

	return false
}

// SetProxyAutoconfigUrl gets a reference to the given string and assigns it to the ProxyAutoconfigUrl field.
func (o *Proxy) SetProxyAutoconfigUrl(v string) {
	o.ProxyAutoconfigUrl = &v
}

// GetFtpProxy returns the FtpProxy field value if set, zero value otherwise.
func (o *Proxy) GetFtpProxy() string {
	if o == nil || o.FtpProxy == nil {
		var ret string
		return ret
	}
	return *o.FtpProxy
}

// GetFtpProxyOk returns a tuple with the FtpProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetFtpProxyOk() (*string, bool) {
	if o == nil || o.FtpProxy == nil {
		return nil, false
	}
	return o.FtpProxy, true
}

// HasFtpProxy returns a boolean if a field has been set.
func (o *Proxy) HasFtpProxy() bool {
	if o != nil && o.FtpProxy != nil {
		return true
	}

	return false
}

// SetFtpProxy gets a reference to the given string and assigns it to the FtpProxy field.
func (o *Proxy) SetFtpProxy(v string) {
	o.FtpProxy = &v
}

// GetHttpProxy returns the HttpProxy field value if set, zero value otherwise.
func (o *Proxy) GetHttpProxy() string {
	if o == nil || o.HttpProxy == nil {
		var ret string
		return ret
	}
	return *o.HttpProxy
}

// GetHttpProxyOk returns a tuple with the HttpProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetHttpProxyOk() (*string, bool) {
	if o == nil || o.HttpProxy == nil {
		return nil, false
	}
	return o.HttpProxy, true
}

// HasHttpProxy returns a boolean if a field has been set.
func (o *Proxy) HasHttpProxy() bool {
	if o != nil && o.HttpProxy != nil {
		return true
	}

	return false
}

// SetHttpProxy gets a reference to the given string and assigns it to the HttpProxy field.
func (o *Proxy) SetHttpProxy(v string) {
	o.HttpProxy = &v
}

// GetNoProxy returns the NoProxy field value if set, zero value otherwise.
func (o *Proxy) GetNoProxy() []string {
	if o == nil || o.NoProxy == nil {
		var ret []string
		return ret
	}
	return o.NoProxy
}

// GetNoProxyOk returns a tuple with the NoProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetNoProxyOk() ([]string, bool) {
	if o == nil || o.NoProxy == nil {
		return nil, false
	}
	return o.NoProxy, true
}

// HasNoProxy returns a boolean if a field has been set.
func (o *Proxy) HasNoProxy() bool {
	if o != nil && o.NoProxy != nil {
		return true
	}

	return false
}

// SetNoProxy gets a reference to the given []string and assigns it to the NoProxy field.
func (o *Proxy) SetNoProxy(v []string) {
	o.NoProxy = v
}

// GetSslProxy returns the SslProxy field value if set, zero value otherwise.
func (o *Proxy) GetSslProxy() string {
	if o == nil || o.SslProxy == nil {
		var ret string
		return ret
	}
	return *o.SslProxy
}

// GetSslProxyOk returns a tuple with the SslProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetSslProxyOk() (*string, bool) {
	if o == nil || o.SslProxy == nil {
		return nil, false
	}
	return o.SslProxy, true
}

// HasSslProxy returns a boolean if a field has been set.
func (o *Proxy) HasSslProxy() bool {
	if o != nil && o.SslProxy != nil {
		return true
	}

	return false
}

// SetSslProxy gets a reference to the given string and assigns it to the SslProxy field.
func (o *Proxy) SetSslProxy(v string) {
	o.SslProxy = &v
}

// GetSocksProxy returns the SocksProxy field value if set, zero value otherwise.
func (o *Proxy) GetSocksProxy() string {
	if o == nil || o.SocksProxy == nil {
		var ret string
		return ret
	}
	return *o.SocksProxy
}

// GetSocksProxyOk returns a tuple with the SocksProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetSocksProxyOk() (*string, bool) {
	if o == nil || o.SocksProxy == nil {
		return nil, false
	}
	return o.SocksProxy, true
}

// HasSocksProxy returns a boolean if a field has been set.
func (o *Proxy) HasSocksProxy() bool {
	if o != nil && o.SocksProxy != nil {
		return true
	}

	return false
}

// SetSocksProxy gets a reference to the given string and assigns it to the SocksProxy field.
func (o *Proxy) SetSocksProxy(v string) {
	o.SocksProxy = &v
}

// GetSocksVersion returns the SocksVersion field value if set, zero value otherwise.
func (o *Proxy) GetSocksVersion() int32 {
	if o == nil || o.SocksVersion == nil {
		var ret int32
		return ret
	}
	return *o.SocksVersion
}

// GetSocksVersionOk returns a tuple with the SocksVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Proxy) GetSocksVersionOk() (*int32, bool) {
	if o == nil || o.SocksVersion == nil {
		return nil, false
	}
	return o.SocksVersion, true
}

// HasSocksVersion returns a boolean if a field has been set.
func (o *Proxy) HasSocksVersion() bool {
	if o != nil && o.SocksVersion != nil {
		return true
	}

	return false
}

// SetSocksVersion gets a reference to the given int32 and assigns it to the SocksVersion field.
func (o *Proxy) SetSocksVersion(v int32) {
	o.SocksVersion = &v
}

func (o Proxy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["proxyType"] = o.ProxyType
	}
	if o.ProxyAutoconfigUrl != nil {
		toSerialize["proxyAutoconfigUrl"] = o.ProxyAutoconfigUrl
	}
	if o.FtpProxy != nil {
		toSerialize["ftpProxy"] = o.FtpProxy
	}
	if o.HttpProxy != nil {
		toSerialize["httpProxy"] = o.HttpProxy
	}
	if o.NoProxy != nil {
		toSerialize["noProxy"] = o.NoProxy
	}
	if o.SslProxy != nil {
		toSerialize["sslProxy"] = o.SslProxy
	}
	if o.SocksProxy != nil {
		toSerialize["socksProxy"] = o.SocksProxy
	}
	if o.SocksVersion != nil {
		toSerialize["socksVersion"] = o.SocksVersion
	}
	return json.Marshal(toSerialize)
}

type NilableProxy struct {
	value *Proxy
	isSet bool
}

func (v NilableProxy) Get() *Proxy {
	return v.value
}

func (v *NilableProxy) Set(val *Proxy) {
	v.value = val
	v.isSet = true
}

func (v NilableProxy) IsSet() bool {
	return v.isSet
}

func (v *NilableProxy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableProxy(val *Proxy) *NilableProxy {
	return &NilableProxy{value: val, isSet: true}
}

func (v NilableProxy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableProxy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


