/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// AnyResponse struct for AnyResponse
type AnyResponse struct {
	Value string `json:"value"`
}

// NewAnyResponse instantiates a new AnyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnyResponse(value string) *AnyResponse {
	this := AnyResponse{}
	this.Value = value
	return &this
}

// NewAnyResponseWithDefaults instantiates a new AnyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnyResponseWithDefaults() *AnyResponse {
	this := AnyResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *AnyResponse) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AnyResponse) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AnyResponse) SetValue(v string) {
	o.Value = v
}

func (o AnyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableAnyResponse struct {
	value *AnyResponse
	isSet bool
}

func (v NilableAnyResponse) Get() *AnyResponse {
	return v.value
}

func (v *NilableAnyResponse) Set(val *AnyResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableAnyResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableAnyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableAnyResponse(val *AnyResponse) *NilableAnyResponse {
	return &NilableAnyResponse{value: val, isSet: true}
}

func (v NilableAnyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableAnyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


