/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// CookieResponse struct for CookieResponse
type CookieResponse struct {
	Value Cookie `json:"value"`
}

// NewCookieResponse instantiates a new CookieResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCookieResponse(value Cookie) *CookieResponse {
	this := CookieResponse{}
	this.Value = value
	return &this
}

// NewCookieResponseWithDefaults instantiates a new CookieResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCookieResponseWithDefaults() *CookieResponse {
	this := CookieResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *CookieResponse) GetValue() Cookie {
	if o == nil {
		var ret Cookie
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CookieResponse) GetValueOk() (*Cookie, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CookieResponse) SetValue(v Cookie) {
	o.Value = v
}

func (o CookieResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableCookieResponse struct {
	value *CookieResponse
	isSet bool
}

func (v NilableCookieResponse) Get() *CookieResponse {
	return v.value
}

func (v *NilableCookieResponse) Set(val *CookieResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableCookieResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableCookieResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableCookieResponse(val *CookieResponse) *NilableCookieResponse {
	return &NilableCookieResponse{value: val, isSet: true}
}

func (v NilableCookieResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableCookieResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


