/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// StatusResponse struct for StatusResponse
type StatusResponse struct {
	Value StatusResponseValue `json:"value"`
}

// NewStatusResponse instantiates a new StatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusResponse(value StatusResponseValue) *StatusResponse {
	this := StatusResponse{}
	this.Value = value
	return &this
}

// NewStatusResponseWithDefaults instantiates a new StatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusResponseWithDefaults() *StatusResponse {
	this := StatusResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *StatusResponse) GetValue() StatusResponseValue {
	if o == nil {
		var ret StatusResponseValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *StatusResponse) GetValueOk() (*StatusResponseValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *StatusResponse) SetValue(v StatusResponseValue) {
	o.Value = v
}

func (o StatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableStatusResponse struct {
	value *StatusResponse
	isSet bool
}

func (v NilableStatusResponse) Get() *StatusResponse {
	return v.value
}

func (v *NilableStatusResponse) Set(val *StatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableStatusResponse(val *StatusResponse) *NilableStatusResponse {
	return &NilableStatusResponse{value: val, isSet: true}
}

func (v NilableStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


