/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// TimeoutsResponse struct for TimeoutsResponse
type TimeoutsResponse struct {
	Value Timeouts `json:"value"`
}

// NewTimeoutsResponse instantiates a new TimeoutsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimeoutsResponse(value Timeouts) *TimeoutsResponse {
	this := TimeoutsResponse{}
	this.Value = value
	return &this
}

// NewTimeoutsResponseWithDefaults instantiates a new TimeoutsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimeoutsResponseWithDefaults() *TimeoutsResponse {
	this := TimeoutsResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *TimeoutsResponse) GetValue() Timeouts {
	if o == nil {
		var ret Timeouts
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *TimeoutsResponse) GetValueOk() (*Timeouts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *TimeoutsResponse) SetValue(v Timeouts) {
	o.Value = v
}

func (o TimeoutsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableTimeoutsResponse struct {
	value *TimeoutsResponse
	isSet bool
}

func (v NilableTimeoutsResponse) Get() *TimeoutsResponse {
	return v.value
}

func (v *NilableTimeoutsResponse) Set(val *TimeoutsResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableTimeoutsResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableTimeoutsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableTimeoutsResponse(val *TimeoutsResponse) *NilableTimeoutsResponse {
	return &NilableTimeoutsResponse{value: val, isSet: true}
}

func (v NilableTimeoutsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableTimeoutsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


