/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// BooleanResponse struct for BooleanResponse
type BooleanResponse struct {
	Value bool `json:"value"`
}

// NewBooleanResponse instantiates a new BooleanResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBooleanResponse(value bool) *BooleanResponse {
	this := BooleanResponse{}
	this.Value = value
	return &this
}

// NewBooleanResponseWithDefaults instantiates a new BooleanResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBooleanResponseWithDefaults() *BooleanResponse {
	this := BooleanResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *BooleanResponse) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BooleanResponse) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BooleanResponse) SetValue(v bool) {
	o.Value = v
}

func (o BooleanResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableBooleanResponse struct {
	value *BooleanResponse
	isSet bool
}

func (v NilableBooleanResponse) Get() *BooleanResponse {
	return v.value
}

func (v *NilableBooleanResponse) Set(val *BooleanResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableBooleanResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableBooleanResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableBooleanResponse(val *BooleanResponse) *NilableBooleanResponse {
	return &NilableBooleanResponse{value: val, isSet: true}
}

func (v NilableBooleanResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableBooleanResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


