/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// RectResponse struct for RectResponse
type RectResponse struct {
	Value Rect `json:"value"`
}

// NewRectResponse instantiates a new RectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRectResponse(value Rect) *RectResponse {
	this := RectResponse{}
	this.Value = value
	return &this
}

// NewRectResponseWithDefaults instantiates a new RectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRectResponseWithDefaults() *RectResponse {
	this := RectResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *RectResponse) GetValue() Rect {
	if o == nil {
		var ret Rect
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *RectResponse) GetValueOk() (*Rect, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *RectResponse) SetValue(v Rect) {
	o.Value = v
}

func (o RectResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableRectResponse struct {
	value *RectResponse
	isSet bool
}

func (v NilableRectResponse) Get() *RectResponse {
	return v.value
}

func (v *NilableRectResponse) Set(val *RectResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableRectResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableRectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableRectResponse(val *RectResponse) *NilableRectResponse {
	return &NilableRectResponse{value: val, isSet: true}
}

func (v NilableRectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableRectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


