/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// PreferenceValue - struct for PreferenceValue
type PreferenceValue struct {
	Bool *bool
	Int32 *int32
	String *string
}

// boolAsPreferenceValue is a convenience function that returns bool wrapped in PreferenceValue
func BoolAsPreferenceValue(v *bool) PreferenceValue {
	return PreferenceValue{
		Bool: v,
	}
}

// int32AsPreferenceValue is a convenience function that returns int32 wrapped in PreferenceValue
func Int32AsPreferenceValue(v *int32) PreferenceValue {
	return PreferenceValue{
		Int32: v,
	}
}

// stringAsPreferenceValue is a convenience function that returns string wrapped in PreferenceValue
func StringAsPreferenceValue(v *string) PreferenceValue {
	return PreferenceValue{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PreferenceValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			match++
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(PreferenceValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(PreferenceValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PreferenceValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PreferenceValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NilablePreferenceValue struct {
	value *PreferenceValue
	isSet bool
}

func (v NilablePreferenceValue) Get() *PreferenceValue {
	return v.value
}

func (v *NilablePreferenceValue) Set(val *PreferenceValue) {
	v.value = val
	v.isSet = true
}

func (v NilablePreferenceValue) IsSet() bool {
	return v.isSet
}

func (v *NilablePreferenceValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilablePreferenceValue(val *PreferenceValue) *NilablePreferenceValue {
	return &NilablePreferenceValue{value: val, isSet: true}
}

func (v NilablePreferenceValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilablePreferenceValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


