/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// NewSessionResponse struct for NewSessionResponse
type NewSessionResponse struct {
	Value NewSessionResponseValue `json:"value"`
}

// NewNewSessionResponse instantiates a new NewSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewSessionResponse(value NewSessionResponseValue) *NewSessionResponse {
	this := NewSessionResponse{}
	this.Value = value
	return &this
}

// NewNewSessionResponseWithDefaults instantiates a new NewSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewSessionResponseWithDefaults() *NewSessionResponse {
	this := NewSessionResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *NewSessionResponse) GetValue() NewSessionResponseValue {
	if o == nil {
		var ret NewSessionResponseValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NewSessionResponse) GetValueOk() (*NewSessionResponseValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *NewSessionResponse) SetValue(v NewSessionResponseValue) {
	o.Value = v
}

func (o NewSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableNewSessionResponse struct {
	value *NewSessionResponse
	isSet bool
}

func (v NilableNewSessionResponse) Get() *NewSessionResponse {
	return v.value
}

func (v *NilableNewSessionResponse) Set(val *NewSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableNewSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableNewSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableNewSessionResponse(val *NewSessionResponse) *NilableNewSessionResponse {
	return &NilableNewSessionResponse{value: val, isSet: true}
}

func (v NilableNewSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableNewSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


