/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// UrlRequest struct for UrlRequest
type UrlRequest struct {
	Url string `json:"url"`
}

// NewUrlRequest instantiates a new UrlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlRequest(url string) *UrlRequest {
	this := UrlRequest{}
	this.Url = url
	return &this
}

// NewUrlRequestWithDefaults instantiates a new UrlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlRequestWithDefaults() *UrlRequest {
	this := UrlRequest{}
	return &this
}

// GetUrl returns the Url field value
func (o *UrlRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *UrlRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *UrlRequest) SetUrl(v string) {
	o.Url = v
}

func (o UrlRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NilableUrlRequest struct {
	value *UrlRequest
	isSet bool
}

func (v NilableUrlRequest) Get() *UrlRequest {
	return v.value
}

func (v *NilableUrlRequest) Set(val *UrlRequest) {
	v.value = val
	v.isSet = true
}

func (v NilableUrlRequest) IsSet() bool {
	return v.isSet
}

func (v *NilableUrlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableUrlRequest(val *UrlRequest) *NilableUrlRequest {
	return &NilableUrlRequest{value: val, isSet: true}
}

func (v NilableUrlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableUrlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


