/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// MobileEmulationDeviceMetrics struct for MobileEmulationDeviceMetrics
type MobileEmulationDeviceMetrics struct {
	Width int32 `json:"width"`
	Height int32 `json:"height"`
	PixelRatio float32 `json:"pixelRatio"`
	Touch bool `json:"touch"`
}

// NewMobileEmulationDeviceMetrics instantiates a new MobileEmulationDeviceMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMobileEmulationDeviceMetrics(width int32, height int32, pixelRatio float32, touch bool) *MobileEmulationDeviceMetrics {
	this := MobileEmulationDeviceMetrics{}
	this.Width = width
	this.Height = height
	this.PixelRatio = pixelRatio
	this.Touch = touch
	return &this
}

// NewMobileEmulationDeviceMetricsWithDefaults instantiates a new MobileEmulationDeviceMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMobileEmulationDeviceMetricsWithDefaults() *MobileEmulationDeviceMetrics {
	this := MobileEmulationDeviceMetrics{}
	var touch bool = true
	this.Touch = touch
	return &this
}

// GetWidth returns the Width field value
func (o *MobileEmulationDeviceMetrics) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *MobileEmulationDeviceMetrics) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *MobileEmulationDeviceMetrics) SetWidth(v int32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *MobileEmulationDeviceMetrics) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *MobileEmulationDeviceMetrics) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *MobileEmulationDeviceMetrics) SetHeight(v int32) {
	o.Height = v
}

// GetPixelRatio returns the PixelRatio field value
func (o *MobileEmulationDeviceMetrics) GetPixelRatio() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PixelRatio
}

// GetPixelRatioOk returns a tuple with the PixelRatio field value
// and a boolean to check if the value has been set.
func (o *MobileEmulationDeviceMetrics) GetPixelRatioOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PixelRatio, true
}

// SetPixelRatio sets field value
func (o *MobileEmulationDeviceMetrics) SetPixelRatio(v float32) {
	o.PixelRatio = v
}

// GetTouch returns the Touch field value
func (o *MobileEmulationDeviceMetrics) GetTouch() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Touch
}

// GetTouchOk returns a tuple with the Touch field value
// and a boolean to check if the value has been set.
func (o *MobileEmulationDeviceMetrics) GetTouchOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Touch, true
}

// SetTouch sets field value
func (o *MobileEmulationDeviceMetrics) SetTouch(v bool) {
	o.Touch = v
}

func (o MobileEmulationDeviceMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["width"] = o.Width
	}
	if true {
		toSerialize["height"] = o.Height
	}
	if true {
		toSerialize["pixelRatio"] = o.PixelRatio
	}
	if true {
		toSerialize["touch"] = o.Touch
	}
	return json.Marshal(toSerialize)
}

type NilableMobileEmulationDeviceMetrics struct {
	value *MobileEmulationDeviceMetrics
	isSet bool
}

func (v NilableMobileEmulationDeviceMetrics) Get() *MobileEmulationDeviceMetrics {
	return v.value
}

func (v *NilableMobileEmulationDeviceMetrics) Set(val *MobileEmulationDeviceMetrics) {
	v.value = val
	v.isSet = true
}

func (v NilableMobileEmulationDeviceMetrics) IsSet() bool {
	return v.isSet
}

func (v *NilableMobileEmulationDeviceMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableMobileEmulationDeviceMetrics(val *MobileEmulationDeviceMetrics) *NilableMobileEmulationDeviceMetrics {
	return &NilableMobileEmulationDeviceMetrics{value: val, isSet: true}
}

func (v NilableMobileEmulationDeviceMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableMobileEmulationDeviceMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


