/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// FindElementResponse struct for FindElementResponse
type FindElementResponse struct {
	Value FindElementResponseValue `json:"value"`
}

// NewFindElementResponse instantiates a new FindElementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindElementResponse(value FindElementResponseValue) *FindElementResponse {
	this := FindElementResponse{}
	this.Value = value
	return &this
}

// NewFindElementResponseWithDefaults instantiates a new FindElementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindElementResponseWithDefaults() *FindElementResponse {
	this := FindElementResponse{}
	return &this
}

// GetValue returns the Value field value
func (o *FindElementResponse) GetValue() FindElementResponseValue {
	if o == nil {
		var ret FindElementResponseValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *FindElementResponse) GetValueOk() (*FindElementResponseValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *FindElementResponse) SetValue(v FindElementResponseValue) {
	o.Value = v
}

func (o FindElementResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NilableFindElementResponse struct {
	value *FindElementResponse
	isSet bool
}

func (v NilableFindElementResponse) Get() *FindElementResponse {
	return v.value
}

func (v *NilableFindElementResponse) Set(val *FindElementResponse) {
	v.value = val
	v.isSet = true
}

func (v NilableFindElementResponse) IsSet() bool {
	return v.isSet
}

func (v *NilableFindElementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableFindElementResponse(val *FindElementResponse) *NilableFindElementResponse {
	return &NilableFindElementResponse{value: val, isSet: true}
}

func (v NilableFindElementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableFindElementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


