/*
Selenium WebDriver

[Selenium WebDriver](https://www.w3.org/TR/webdriver) API specification

API version: 1.0.0
Contact: support@aerokube.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// MoonMobileDevice struct for MoonMobileDevice
type MoonMobileDevice struct {
	DeviceName string `json:"deviceName"`
	Orientation *string `json:"orientation,omitempty"`
}

// NewMoonMobileDevice instantiates a new MoonMobileDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoonMobileDevice(deviceName string) *MoonMobileDevice {
	this := MoonMobileDevice{}
	this.DeviceName = deviceName
	var orientation string = "portrait"
	this.Orientation = &orientation
	return &this
}

// NewMoonMobileDeviceWithDefaults instantiates a new MoonMobileDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoonMobileDeviceWithDefaults() *MoonMobileDevice {
	this := MoonMobileDevice{}
	var orientation string = "portrait"
	this.Orientation = &orientation
	return &this
}

// GetDeviceName returns the DeviceName field value
func (o *MoonMobileDevice) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *MoonMobileDevice) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *MoonMobileDevice) SetDeviceName(v string) {
	o.DeviceName = v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *MoonMobileDevice) GetOrientation() string {
	if o == nil || o.Orientation == nil {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoonMobileDevice) GetOrientationOk() (*string, bool) {
	if o == nil || o.Orientation == nil {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *MoonMobileDevice) HasOrientation() bool {
	if o != nil && o.Orientation != nil {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *MoonMobileDevice) SetOrientation(v string) {
	o.Orientation = &v
}

func (o MoonMobileDevice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["deviceName"] = o.DeviceName
	}
	if o.Orientation != nil {
		toSerialize["orientation"] = o.Orientation
	}
	return json.Marshal(toSerialize)
}

type NilableMoonMobileDevice struct {
	value *MoonMobileDevice
	isSet bool
}

func (v NilableMoonMobileDevice) Get() *MoonMobileDevice {
	return v.value
}

func (v *NilableMoonMobileDevice) Set(val *MoonMobileDevice) {
	v.value = val
	v.isSet = true
}

func (v NilableMoonMobileDevice) IsSet() bool {
	return v.isSet
}

func (v *NilableMoonMobileDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNilableMoonMobileDevice(val *MoonMobileDevice) *NilableMoonMobileDevice {
	return &NilableMoonMobileDevice{value: val, isSet: true}
}

func (v NilableMoonMobileDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NilableMoonMobileDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


